### ISSUE TITLE
UnsatisfiedLinkError: Unable to load library 'CoreServices': Native library (darwin/libCoreServices.dylib) not found in resource path 

### ISSUE THREAD

**Issue by benfry** [fathominfo/processing-p5js-mode#26]
Seen in class this morning; seems to be a problem with Big Sur and old JNA releases. 

Updating to JNA 5.7.0 in the hope that fixes it. 

```
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Unable to load library 'CoreServices': Native library (darwin/libCoreServices.dylib) not found in resource path ([file:/Applications/Processing.app/Contents/Java/, file:/Applications/Processing.app/Contents/Java/ant.jar, file:/Applications/Processing.app/Contents/Java/ant-launcher.jar, file:/Applications/Processing.app/Contents/Java/core.jar, file:/Applications/Processing.app/Contents/Java/jna.jar, file:/Applications/Processing.app/Contents/Java/pde.jar, file:/Applications/Processing.app/Contents/Java/jna-platform.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
	at com.sun.jna.platform.mac.MacFileUtils$FileManager.<clinit>(MacFileUtils.java:35)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at com.sun.jna.Native.loadLibraryInstance(Native.java:527)
	at com.sun.jna.Native.getLibraryOptions(Native.java:588)
	at com.sun.jna.Native.getStructureAlignment(Native.java:676)
	at com.sun.jna.Structure.setAlignType(Structure.java:259)
	at com.sun.jna.Structure.<init>(Structure.java:176)
	at com.sun.jna.Structure.<init>(Structure.java:172)
	at com.sun.jna.Structure.<init>(Structure.java:159)
	at com.sun.jna.Structure.<init>(Structure.java:151)
	at com.sun.jna.platform.mac.MacFileUtils$FileManager$FSRef.<init>(MacFileUtils.java:46)
	at com.sun.jna.platform.mac.MacFileUtils.moveToTrash(MacFileUtils.java:69)
	at processing.app.Platform.deleteFile(Platform.java:378)
	at processing.mode.p5js.p5jsBuild.cleanTempFiles(p5jsBuild.java:246)
	at processing.mode.p5js.p5jsEditor.handleStop(p5jsEditor.java:372)
	at processing.mode.p5js.p5jsEditor.internalCloseRunner(p5jsEditor.java:306)
	at processing.app.ui.Editor.prepareRun(Editor.java:2809)
	at processing.mode.p5js.p5jsEditor.handleRun(p5jsEditor.java:337)
	at processing.mode.p5js.p5jsToolbar.handleRun(p5jsToolbar.java:32)
	at processing.app.ui.EditorToolbar$1.actionPerformed(EditorToolbar.java:157)
	at processing.app.ui.EditorButton.mousePressed(EditorButton.java:190)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by benfry** [comment]
Attempting to fix in 4 alpha 4 with https://github.com/processing/processing4/commit/2ecde3af1a8aa1ee5fcd6369acfa04884477ae25

**Comment by mchangxe** [comment]
@benfry hey ben, is this resolved in next upcoming alpha release? I need to export one of my applications out right now and I am on alpha 3. When is alpha 4 coming out?
