### ISSUE TITLE
Failed to mail or browse http://127.0.0.1:8473/. Error code: -600

### ISSUE THREAD

**Issue by benfry** [fathominfo/processing-p5js-mode#4]
Seen in class this morning. First thought it was a broken OS install or needed a reboot. Now thinking it might be an i18n/l10n issue.

```
java.io.IOException: Failed to mail or browse http://127.0.0.1:8473/. Error code: -600
    at sun.lwawt.macosx.CDesktopPeer.lsOpen(CDesktopPeer.java:72)
    at sun.lwawt.macosx.CDesktopPeer.browse(CDesktopPeer.java:65)
    at java.awt.Desktop.browse(Desktop.java:386)
    at processing.app.platform.DefaultPlatform.openURL(DefaultPlatform.java:114)
    at processing.app.Platform.openURL(Platform.java:149)
    at processing.app.ui.EditorStatus$1.mousePressed(EditorStatus.java:109)
    at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
```

**Comment by benfry** [comment]
-600 is an OS error: “Application isn’t running” (suggesting that the reboot may be the issue...) 

Or wondering if the toURI() function is failing us, i.e. something different is used with / or : on Hebrew systems.

**Comment by benfry** [comment]
This was a hung copy of Safari. Need to have a better error message to let the user know what's happening.

**Comment by benfry** [comment]
Fixing upstream in 3.2.3 or 3.3.
